### ISSUE TITLE
get_trade_transactions

### ISSUE THREAD

**Issue by MiguelInza** [caiyundong/bitbay_api_python#2]
Hello,

when using the def get_trade_transactions I have this error message:

('get_trade_transactions', {u'status': u'Fail', u'errors': [u'INVALID_HASH_SIGNATURE']})

Do you know why?

    def get_trade_transactions(self, markets, rateFrom, rateTo, fromTime, toTime, userAction, nextPageCursor):
        """
        :param markets:
        :param rateFrom:
        :param rateTo:
        :param fromTime:
        :param toTime:
        :param userAction: buy/sell
        :param nextPageCursor:  start
        :return:
        """
        request = {"markets": markets, "rateFrom": rateFrom, "rateTo": rateTo, "fromTime": fromTime, "toTime": toTime, "userAction": userAction, "nextPageCursor": nextPageCursor}
        response = self.query_private("GET", URL + "/trading/history/transactions", req=request)
        return response

**Comment by caiyundong** [comment]
hi, 

I have fixed the code. 

Something with the private-get.

Please give a try and let me know if not working.

regards,
yundong

**Comment by MiguelInza** [comment]
Yes, now is working.
Thank you very much.

**Comment by caiyundong** [comment]
you are welcome

**Comment by MiguelInza** [comment]
Hello again,

some months ago you help me with my Bitbay bot for API Rest in Python.
I'm trying to learn more Python but it's difficult for me.
Do you have a bot to get the Bitbay Orderbook using Websocket?
And the Balance?

Thanks in advance.

Best regards.

Miguel Inza.
